trigger:
  branches:
    include:
      - main

jobs:
  - job: RemoveCustomOwnerRoles
    displayName: Remove Custom Owner Roles
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI - Remove Custom Owner Roles
        inputs:
          azureSubscription: 'Azure for Students(a2b3f557-85a6-4ffc-aff7-676ca947f357)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: '# Remove custom owner roles logic here'


