trigger:
  branches:
    include:
      - main

jobs:
  - job: BuildAndDeploy
    displayName: Build and Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: echo "Building the project..."
        displayName: 'Build'
      
      - script: echo "Running tests..."
        displayName: 'Test'

      - script: echo "Publishing artifacts..."
        displayName: 'Publish'
        # You can publish the build artifacts to a storage location or package feed

      - script: echo "Deploying the application..."
        displayName: 'Deploy'
        # You can use deployment scripts or deployment tasks to deploy the application

      - script: echo "Pipeline completed successfully!"
        displayName: 'Complete'
