trigger:
  branches:
    include:
      - main

jobs:
  - job: RemoveCustomOwnerRoles
    displayName: Remove Custom Owner Roles
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI - Remove Custom Owner Roles
        inputs:
          azureSubscription: 'Azure for Students'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Remove custom owner roles logic here

  - job: AssignAdminRoleForResourceLocking
    displayName: Assign Admin Role for Resource Locking
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI - Assign Admin Role
        inputs:
          azureSubscription: '<Azure subscription>'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Assign admin role for resource locking logic here
